name: 'Semantic Versioning'
description: 'Tag commits according to semantic versioning'
inputs:
  repo-token:
    required: true
    description: 'The GITHUB_TOKEN secret'
  release:
    required: false
    default: 'false'
    description: 'If true creates a new tag and release, otherwise just calculates the next version'
  version-prefix:
    required: false
    default: ''
    description: 'The prefix to be used on tags. i.e. v for v1.0.1'
  major-version:
    required: false
    default: '0'
    description: 'Allows to control how the next version is calculated, if set to a value > than the current major version, the next version will be major-version.0.0'
  sha:
    required: false
    default: ''
    description: 'Sha identifier of the commit to release, if not provided then the commit triggering the action is used'
  release-branch:
    required: false
    default: ''
    description: 'DEPRECATED: use release instead. The branch from which releases are allowed (default master)'
outputs:
  next-version:
    description: 'The next calculated version'
  reference:
    description: 'The tag name if release=true otherwise the branch name'
runs:
  using: 'node16'
  main: 'dist/index.js'
