name: 'Semantic Versioning'
description: 'Tag commits according to semantic versioning'
inputs:
  repo-token:
    required: true
    description: 'The GITHUB_TOKEN secret'
  release:
    required: false
    default: 'false'
    description: 'If true creates a new tag and release, otherwise just calculates the next version'
  version-prefix:
    required: false
    default: ''
    description: 'The prefix to be used on tags. i.e. v for v1.0.1'
  sha:
    required: false
    default: ''
    description: 'Sha identifier of the commit to release, if not provided then the commit triggering the action is used'
  release-branch:
    required: false
    default: 'master'
    description: 'The branch from which releases are allowed (default master)'
outputs:
  next-version:
    description: 'The next calculated version'
runs:
  using: 'node12'
  main: 'dist/index.js'
