name: PR

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'dist/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: test
        run: npm test
      - name: compile
        run: npm run package
      - name: run action
        id: semver
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version-prefix: v
          release: false
          major-version: 2
      - name: debug
        run: |
          echo "next-version: ${{ steps.semver.outputs.next-version }}"
          echo "reference: ${{ steps.semver.outputs.reference }}"
          echo "major: ${{ steps.semver.outputs.major }}"
          echo "minor: ${{ steps.semver.outputs.minor }}"
          echo "patch: ${{ steps.semver.outputs.patch }}"
