name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'dist/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: test
        run: npm test
      - name: compile
        run: npm run package
      - name: commit package
        id: package
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git diff --quiet && git diff --staged --quiet || (git commit -am 'compiled action' && git push)
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: release
        uses: ./
        id: semver
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version-prefix: v
          release: true
          sha: ${{ steps.package.outputs.sha }}
          major-version: 2
